spring:
  application:
    name: shortyurl


  datasource:
    url: jdbc:postgresql://localhost:5432/shortyurldb
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true